# Tensor算术操作

In [1]:
import torch

tensor = torch.ones((2, 2))
print(tensor + 2) # 张量与标量相加
print(tensor - 1) # 张量与标量相减
print(tensor * 3) # 张量与标量相乘
print(tensor / 2) # 张量与标量相除

tensor([[3., 3.],
        [3., 3.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
